In [27]:
import numpy as np

n_points_aperture = 5
n_points_time = 5

indices = np.array(range(n_points_aperture*n_points_time))
index_grid = indices.reshape(n_points_time, n_points_aperture)
v1 = index_grid[:, :-1]                       
v2 = index_grid[:, 1:]                         
v3 = np.roll(index_grid, -1, axis=0)[:, 1:]     
v4 = np.roll(index_grid, -1, axis=0)[:, :-1]    
# Stack the adjusted indices to form faces with vertical wrapping
faces = np.stack((v1, v2, v3, v4), axis=-1).reshape(-1, 4)
print(faces)

[[ 0  1  6  5]
 [ 1  2  7  6]
 [ 2  3  8  7]
 [ 3  4  9  8]
 [ 5  6 11 10]
 [ 6  7 12 11]
 [ 7  8 13 12]
 [ 8  9 14 13]
 [10 11 16 15]
 [11 12 17 16]
 [12 13 18 17]
 [13 14 19 18]
 [15 16 21 20]
 [16 17 22 21]
 [17 18 23 22]
 [18 19 24 23]
 [20 21  1  0]
 [21 22  2  1]
 [22 23  3  2]
 [23 24  4  3]]


In [30]:
import numpy as np

# Example NumPy array
array = np.arange(100)  # An array with 100 elements

# Concatenate the first 20 and the last 20 elements in one step
result = np.concatenate((array[:20], array[-20:]))

print(result)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 80 81 82 83
 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
